version: '3.3'

services:

    collabora:
        image: collabora/code
        container_name: collabora
        ports:
            - "8200:9980"
        restart: unless-stopped
        environment:
            - extra_params=--o:ssl.enable=false
            - username=admin
            - password=p4ssw0rd
            - dictionaries=es_ES 
            - TZ=Europe/Madrid            
            
            
